# -*- coding: utf-8 -*-
"""Saúde - Recomendação de atividade fisica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnMzAEKKaouuN0PZij1Qqr2Q9aICAM4q
"""

import pandas as pd
from io import StringIO
from collections import defaultdict
import re

# Dados baseados na imagem, estruturados em formato transacional (Objetivo + Exercícios)
dados_treino_str = """
ID_Usuario,Itens
1,Massa,Levantamento_Peso,Flexao,Rosca_Direta,Supino
2,Peso,Corrida,Yoga,Pular_Corda,HIIT
3,Forca,Levantamento_Peso,Rosca_Direta,Barra_Fixa,Agachamento
4,Resistencia,Corrida,Ciclismo,Eliptico,Natacao
5,Definicao,Flexao,Abdominal,Agachamento,Barra_Fixa
6,Condicionamento,Escalada,Natacao,Corrida,HIIT
7,Pos_Lesao,Yoga,Alongamento,Ciclismo
8,Massa,Levantamento_Peso,Supino,Rosca_Direta
9,Peso,HIIT,Pular_Corda,Corrida,Yoga
10,Forca,Barra_Fixa,Rosca_Direta,Agachamento,Levantamento_Peso
11,Resistencia,Ciclismo,Natacao,Corrida,Eliptico
12,Definicao,Abdominal,Flexao,Barra_Fixa,Agachamento
13,Condicionamento,Escalada,Natacao,Corrida,HIIT
14,Pos_Lesao,Alongamento,Yoga,Ciclismo
15,Massa,Rosca_Direta,Supino,Levantamento_Peso,Agachamento
"""

# FIX: Processar a string diretamente para evitar o erro de float/NaN do pandas
transacoes = []
linhas = dados_treino_str.strip().split('\n')[1:] # Ignora o cabeçalho

for linha in linhas:
    # Divide por vírgula e remove o ID_Usuario (primeiro elemento)
    itens = [item.strip() for item in linha.split(',')[1:] if item.strip()]
    if itens:
        transacoes.append(itens)

# Lista de Objetivos de Treino (para análise focada)
OBJETIVOS = ['Massa', 'Peso', 'Forca', 'Resistencia', 'Definicao', 'Condicionamento', 'Pos_Lesao']

print("--- Transações de Treino Prontas para Mineração ---")
print(f"Total de Transações: {len(transacoes)}")
print(f"Exemplo de Transação (Usuário 1): {transacoes[0]}\n")

def simular_mineracao_regras(transacoes, objetivo_foco, min_confianca=0.70):

    contagem_itens = defaultdict(int)
    for transacao in transacoes:
        for item in transacao:
            contagem_itens[item] += 1

    regras_candidatas = {}

    # Suporte do Antecedente (Objetivo)
    suporte_objetivo = sum(1 for transacao in transacoes if objetivo_foco in transacao)

    # 2. Calcular a Frequência (Suporte) do Itemset {Objetivo, Exercício}
    for item_ex in contagem_itens.keys():
        if item_ex not in OBJETIVOS:

            suporte_conjunto = 0

            for transacao in transacoes:
                # Transação deve conter o Objetivo e o Exercício
                if objetivo_foco in transacao and item_ex in transacao:
                    suporte_conjunto += 1

            # Evita divisão por zero
            if suporte_objetivo > 0:
                # Confiança = Suporte(Objetivo & Exercício) / Suporte(Objetivo)
                confianca = suporte_conjunto / suporte_objetivo
                regras_candidatas[item_ex] = confianca

    # 3. Filtrar Regras por Confiança Mínima
    regras_finais = {
        ex: conf
        for ex, conf in regras_candidatas.items()
        if conf >= min_confianca
    }

    # 4. Ordenar por Confiança
    regras_ordenadas = dict(sorted(regras_finais.items(), key=lambda item: item[1], reverse=True))

    return regras_ordenadas

# --- Função de Recomendação Final ---
def gerar_recomendacao(objetivo):
    regras = simular_mineracao_regras(transacoes, objetivo, min_confianca=0.75)

    if regras:
        print(f"\n--- 🎯 Recomendação Personalizada para: {objetivo} ---")
        for exercicio, confianca in regras.items():
            print(f"-> {exercicio} (Confiança na Regra: {confianca:.2f})")
        print("--------------------------------------------------")
    else:
        print(f"\nNão foram encontradas regras fortes (Confiança > 0.75) para o objetivo: {objetivo}.")

# 1. Ganho de Massa Muscular
gerar_recomendacao('Massa')

# 2. Perda de Peso
gerar_recomendacao('Peso')

# 3. Recuperação Pós-Lesão
gerar_recomendacao('Pos_Lesao')